repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["-f", "-S", "*.csv,*.png"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff-check
        args: [--fix, --preview]
      - id: ruff-format
        args: [--preview]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy f1_visualization dashboard
        language: system
        exclude: ^tests/
        pass_filenames: false
